#!/bin/sh

echo "Pre commit hook execution started.."

if [ "$(git config --get devsecops.gitleaks.enabled)" != "true" ]; then
    echo "devsecops.gitleaks-parameter is not enabled. Checking is skipped!"
    exit 0
fi

echo "ToDo: Implement checking!"
